
def sum_of_arithmetic_series(a, d, n):
    """
    Sum of an arithmetic series.
    Or the sum of a series generated by summing
    each element from a_k = a_0 + d * k
    e.g.
    Input : a = 1
            d = 3
            n = 4
    Output : 22
    1 + 4 + 7 + 10 = 22
    """
    sum_ = 0
    i = 0
    while i < n:
        sum_ = sum_ + a
        a = a + d
        i = i + 1
    return sum_
